HippieTamTam/Models/Layout.cs
namespace HippieTamTam.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Layout")]
    public partial class Layout
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Layout()
        {
            Post = new HashSet<Post>();
        }

        public int LayoutID { get; set; }

        [Required]
        [StringLength(100)]
        public string LayoutName { get; set; }

        public int CategoryID { get; set; }

        public virtual Category Category { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post> Post { get; set; }
    }
}

HippieTamTam/Controllers/BlogPostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HippieTamTam.Models;

namespace HippieTamTam.Controllers
{
    public class BlogPostController : Controller
    {
        BlogDatabaseContext DbData = new BlogDatabaseContext();
        // GET: BlogPost
        public ActionResult Post(int id)
        {
            var Post = DbData.Posts.Where(p=>p.PostID==id).SingleOrDefault();
            var layout = Post.Layout.LayoutName;

            if (Post.Category.CategoryName=="Afirmacije")
            {
                return View("Post", "~/Views/Shared/Afirmacije/" + layout + ".cshtml", Post);
            }
            else
            {
                return View("Post", "~/Views/Shared/Pesme/" + layout + ".cshtml", Post);
            }
            
        }
    }
}

HippieTamTam/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />

    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    
</head>
<body>
   
       @RenderBody()

   

    
@*footer start*@

<footer class="b-footer">
    <div class="b-container">
       
    </div>
</footer>

@*footer end*@
    
    
    
</body>
</html>

HippieTamTam/Views/Shared/_sub1-txt1-bimg1.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />

    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>

    @RenderBody()
    @*header*@

    <header class="blog-featured" style="background:url(@Url.Content(Model.PostBackground) )@Url.Content(Model.PostBackgroundColor);">
        <div class="b-container">
            <div class="headline">
                <h1>@Model.PostTitle </h1>
                <p class="meta">
                    <span>@Model.PostAuthor</span>
                    &nbsp;|&nbsp; @Model.PostDateCreated.ToString("MMM d, yyyy")
                </p>
            </div>
        </div>
    </header>

    @*header end*@

    @*social networks*@
    <section class="share-this-post"></section>
    @*social networks end*@

    @*post content*@

    <section id="post-content" class="b-container">

        <div class="blog-post">
            @*first paragraph reserved for title*@
            <p>
                @Model.PostSubhead1
                
            </p>
            @*first paragraph end*@
            <p>
                @Model.PostText1
            </p>
            <figure>
                <img src="@Url.Content(Model.PostBigImage1)" class="big-image" />
                <em class="img-text">
                   @Model.PostBigImageText1
                </em>
            </figure>
            
        </div>
    </section>
    @*post content end*@

    @*most popular section*@
    <section class="most-popular">
        <div class="most-popular-container">
            <header>
                <h2>
                    <span>najpopularnije</span>
                </h2>
            </header>
            <div class="row-flex">
                <div class="col-md-4 col-sm-4 col-lg-4 col-xs-6 post">
                    <a href="@Url.Action("Post","BlogPost")" class="post-box">
                        <figure>
                            <img src="~/Images/employee-identity.png" class="post-img" />
                        </figure>
                        <p>
                            <span class="category">
                                Afirmacije
                            </span>
                            <br>
                            Vi ste super muškarac ili super žena u svakom trenutku.

                        </p>
                    </a>
                </div>
                <div class="col-md-4 col-sm-4 col-lg-4 col-xs-6 post">
                    <a href="#" class="post-box">
                        <figure>
                            <img src="~/Images/brand-strategy.png" class="post-img" />
                        </figure>
                        <p>
                            <span class="category">
                                Afirmacije
                            </span>
                            <br>
                            Ljubav koja počiva na plemenitim motivima,
                            traje večno.

                        </p>
                    </a>
                </div>
                <div class="col-md-4 col-sm-4 col-lg-4 col-xs-6 post">
                    <a href="#" class="post-box">
                        <figure>
                            <img src="~/Images/insincere-support.png" class="post-img" />
                        </figure>
                        <p>
                            <span class="category">
                                Afirmacije
                            </span>
                            <br>
                            Vole cure kad Brkovi Zare i Goci.

                        </p>
                    </a>
                </div>
            </div>
        </div>
    </section>
    @*most popular end*@


    @*footer start*@

    <footer class="b-footer">
        <div class="b-container">

        </div>
    </footer>

    @*footer end*@
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

HippieTamTam/Views/Shared/_sub1-txt1-txt2-quo1.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />

    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>

@RenderBody()
@*header*@

<header class="blog-featured" style="background:url(@Url.Content(Model.PostBackground) )@Url.Content(Model.PostBackgroundColor);">
    <div class="b-container">
        <div class="headline">
            <h1>@Model.PostTitle </h1>
            <p class="meta">
                <span>@Model.PostAuthor</span>
                &nbsp;|&nbsp; @Model.PostDateCreated.ToString("MMM d, yyyy")
            </p>
        </div>
    </div>
</header>

@*header end*@

@*social networks*@
<section class="share-this-post"></section>
@*social networks end*@

@*post content*@

<section id="post-content" class="b-container">

    <div class="blog-post">
        <p>
            @Model.PostSubhead1
        </p>
        <p>
            @Model.PostText1
        </p>
        <p>
            @Model.PostText2
        </p>
        <blockquote>
            @Model.PostQuote1
        </blockquote>
    </div>
</section>
@*post content end*@

@*most popular section*@
<section class="most-popular">
    <div class="most-popular-container">
        <header>
            <h2>
                <span>najpopularnije</span>
            </h2>
        </header>
        <div class="row-flex">
            <div class="col-md-4 col-sm-4 col-lg-4 col-xs-6 post">
                <a href="@Url.Action("Post","BlogPost")" class="post-box">
                    <figure>
                        <img src="~/Images/employee-identity.png" class="post-img" />
                    </figure>
                    <p>
                        <span class="category">
                            Afirmacije
                        </span>
                        <br>
                        Vi ste super muškarac ili super žena u svakom trenutku.

                    </p>
                </a>
            </div>
            <div class="col-md-4 col-sm-4 col-lg-4 col-xs-6 post">
                <a href="#" class="post-box">
                    <figure>
                        <img src="~/Images/brand-strategy.png" class="post-img" />
                    </figure>
                    <p>
                        <span class="category">
                            Afirmacije
                        </span>
                        <br>
                        Ljubav koja počiva na plemenitim motivima,
                        traje večno.

                    </p>
                </a>
            </div>
            <div class="col-md-4 col-sm-4 col-lg-4 col-xs-6 post">
                <a href="#" class="post-box">
                    <figure>
                        <img src="~/Images/insincere-support.png" class="post-img" />
                    </figure>
                    <p>
                        <span class="category">
                            Afirmacije
                        </span>
                        <br>
                        Vole cure kad Brkovi Zare i Goci.

                    </p>
                </a>
            </div>
        </div>
    </div>
</section>
@*most popular end*@


    @*footer start*@

    <footer class="b-footer">
        <div class="b-container">
            
        </div>
    </footer>

    @*footer end*@
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>